-- schema.sql
-- Normalized OBE syllabus database (SQLite).
--
--   courses
--     |-- course_outcomes
--     '-- weekly_schedules
--           '-- lesson_outcomes
--
-- NOTE: foreign key enforcement is turned on per connection in db_manager.py
-- (SQLite requires "PRAGMA foreign_keys = ON" every time a connection opens).

CREATE TABLE IF NOT EXISTS courses (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    course_code   TEXT    NOT NULL UNIQUE,
    course_title  TEXT    NOT NULL,
    description   TEXT    NOT NULL,
    units         INTEGER NOT NULL CHECK (units BETWEEN 1 AND 6),
    prerequisite  TEXT    NOT NULL DEFAULT 'None',
    created_at    TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS course_outcomes (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    course_id     INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    number        INTEGER NOT NULL CHECK (number >= 1),
    domain        TEXT    NOT NULL CHECK (domain IN ('K', 'S', 'A')),
    text          TEXT    NOT NULL CHECK (length(trim(text)) > 0),  -- current (possibly human-edited) wording
    original_text TEXT    NOT NULL,                                 -- wording as generated by the AI
    UNIQUE (course_id, number)
);

CREATE TABLE IF NOT EXISTS weekly_schedules (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    course_id     INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    week          INTEGER NOT NULL CHECK (week BETWEEN 1 AND 18),
    topic         TEXT    NOT NULL CHECK (length(trim(topic)) > 0),
    description   TEXT    NOT NULL,
    UNIQUE (course_id, week)
);

CREATE TABLE IF NOT EXISTS lesson_outcomes (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    schedule_id   INTEGER NOT NULL REFERENCES weekly_schedules(id) ON DELETE CASCADE,
    domain        TEXT    NOT NULL CHECK (domain IN ('K', 'S', 'A')),
    text          TEXT    NOT NULL CHECK (length(trim(text)) > 0),
    original_text TEXT    NOT NULL
);

-- Speeds up "all lesson outcomes of a week" and cascading deletes.
CREATE INDEX IF NOT EXISTS idx_lesson_outcomes_schedule ON lesson_outcomes(schedule_id);